"""create initial schema

Revision ID: d92643fc766c
Revises:
Create Date: 2026-08-15 18:47:53.072993

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d92643fc766c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anonymous_players",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("best_endless_score", sa.Integer(), nullable=False),
        sa.Column("total_games_played", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("display_name"),
    )
    op.create_table(
        "cached_words",
        sa.Column("word", sa.String(length=120), nullable=False),
        sa.Column("article", sa.String(length=8), nullable=True),
        sa.Column("part_of_speech", sa.String(length=80), nullable=False),
        sa.Column("meaning", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("word"),
    )
    op.create_table(
        "reading_passages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("group", sa.String(length=40), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("part", sa.String(length=40), nullable=True),
        sa.Column("exercise_type", sa.String(length=80), nullable=True),
        sa.Column("topic", sa.String(length=80), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("passage_text", sa.Text(), nullable=False),
        sa.Column("content_json", sa.Text(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "focus_word_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("word", sa.String(length=120), nullable=False),
        sa.Column("topic", sa.String(length=80), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word"],
            ["cached_words.word"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("word", "topic", "level", name="uq_focus_word_topic_level"),
    )
    op.create_table(
        "quiz_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("player_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=40), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("ended_reason", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["anonymous_players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reading_questions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("passage_id", sa.String(length=36), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["reading_passages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quiz_attempt_questions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("word", sa.String(length=120), nullable=False),
        sa.Column("question_type", sa.String(length=40), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("correct_answer", sa.String(length=160), nullable=False),
        sa.Column("choices_json", sa.Text(), nullable=False),
        sa.Column("selected_answer", sa.String(length=160), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("answered_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["quiz_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", "id", name="uq_attempt_question"),
    )
    op.create_table(
        "reading_answers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["reading_questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reading_answers")
    op.drop_table("quiz_attempt_questions")
    op.drop_table("reading_questions")
    op.drop_table("quiz_attempts")
    op.drop_table("focus_word_entries")
    op.drop_table("reading_passages")
    op.drop_table("cached_words")
    op.drop_table("anonymous_players")
    # ### end Alembic commands ###
